### ISSUE TITLE
How to run the server and cli as there is no service defined for server in docker-compose.yml

### ISSUE THREAD

**Issue by Irfanwani** [nmengual/code-push-server#1]
I ran the server in docker and as there is only redis service defined, how is it supposed to work. I tried to run the cli, tried registering by running code-push-standalone register, it opens `localhost:3000/<rest_of_url>` but it shows `site cannot be reached` as it is not up. So how to make it work. Do i need to define a separate service for that in docker-compose.yml?

**Comment by Irfanwani** [comment]
Ran redis in docker and ran the server as mentioned in readme.md of api.

**Comment by amdrade** [comment]
`socket hang up` for me
